package_update: true
package_upgrade: true
packages:
  - wget
  - build-essentials
runcmd:
  - [sudo, DEBIAN_FRONTEND=noninteractive, apt, install, --assume-yes, xfce4]
  - [
      wget,
      https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb,
      -P,
      /tmp,
    ]
  - [sudo, apt, install, -y, /tmp/chrome-remote-desktop_current_amd64.deb]
  - [sudo, snap, install, intellij-idea-community, --classic]
